### ISSUE TITLE
invalid cookie

### ISSUE THREAD

**Issue by palewire** [tappleby/slack_auth_proxy#2]
Hello. Great idea for a library!

I've started to get it try and get it going by configuring a blank cloud server with the code. But I've run into a problem. After completing the OAuth loop with Slack, I get the following error:

```bash
2016/11/23 21:26:18 invalid cookie
```

Any ideas what I'm doing wrong?

I'm trying this get this going without SSL just as a start. Here's my config.yml and nginx conf.

```yml
client_id: <myid>
client_secret: <mysecret>
slack_team: <myteam>

redirect_uri: http://<amazon ec2 server public IP>/oauth2/callback/

cookie_hash_key: <my the slack_auth_proxy function generated>
cookie_block_key: <my the slack_auth_proxy function generated>

upstreams:
  - host: "<the URL to a private S3 bucket I want to let users view via the proxy>"
```

```text
server {
    listen 80;
    server_name <amazon ec2 server public IP>;
    add_header Strict-Transport-Security max-age=2592000;

    location / {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
    }
}
```
